# Generated by Django 3.1.4 on 2021-04-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='email_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='current_bal',
            field=models.IntegerField(default=2000),
        ),
    ]
