# Generated by Django 3.1.4 on 2021-04-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20210415_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createuser',
            old_name='current_bal',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='createuser',
            old_name='branch_name',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='createuser',
            old_name='email_id',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='createuser',
            old_name='user_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='createuser',
            name='account',
            field=models.IntegerField(default=0),
        ),
    ]
