# Generated by Django 3.1.4 on 2021-04-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20210416_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.IntegerField(default=2000)),
                ('receiver', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
    ]
