# Generated by Django 3.1.4 on 2021-04-15 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_transfermoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfermoney',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transfermoney',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
