# Generated by Django 3.1.4 on 2021-04-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
