# Generated by Django 3.1.4 on 2021-04-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
